name: Deploy Hugo site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Install Hugo
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'  # same version as my local build
          extended: true

      # Build site using vendored modules
      - name: Build
        run: |
          hugo --gc --minify --ignoreCache

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
